<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--En este archivo se declaran las propiedades inerciales de los componentes
    para la simulación, también se declaran las dimensiones de las piezas -->

    <!-- Definiciones de dimensiones y otros parámetros -->
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="base_mass" value="20"/>
    <xacro:property name="base_radius" value="0.15"/>
    <xacro:property name="base_length" value="0.15"/>
    <xacro:property name="link1_mass" value="5"/>
    <xacro:property name="link1_radius" value="0.05"/>
    <xacro:property name="link1_length" value="0.4"/>

    <xacro:property name="link2_mass" value="2"/>
    <xacro:property name="link2_radius" value="0.05"/>
    <xacro:property name="link2_length" value="0.3"/>

    <xacro:property name="link3_mass" value="3"/>
    <xacro:property name="link3_radius" value="0.025"/>
    <xacro:property name="link3_length" value="0.3"/>

    <xacro:property name="link4_mass" value="1"/>
    <xacro:property name="link4_radius" value="0.025"/>
    <xacro:property name="link4_length" value="0.15"/>

    <!-- Macro para la definición de la inercia de las piezas -->
    <xacro:macro name="inertial_block" params="mass length radius">
        <inertial>
            <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia
                ixx="${mass / 12.0 * (2*radius*2*radius + length*length)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (length*length + 2*radius*2*radius)}" iyz="0.0"
                izz="${mass / 12.0 * (2*radius*2*radius + 2*radius*2*radius)}" />
        </inertial>
    </xacro:macro>

    <!-- Macro para definir la visualización del modelo, en otras palabras, cómo se verán las piezas en el simulador -->
    <xacro:macro name="visual_block" params="radius length color">
        <visual>
            <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${radius}" length="${length}"/>
            </geometry>
            <material name="grey">
                <color rgba="${color}"/>
            </material>
        </visual>
    </xacro:macro>

    <!-- Macro para definir las propiedades de colisión de las piezas -->
    <xacro:macro name="collision_block" params="radius length">
        <collision>
            <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${radius}" length="${length}"/>
            </geometry>
        </collision>
    </xacro:macro>
</robot>