controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

    write_op_modes:
      - joint_1
      - joint_2
      - joint_3
    
    interface_name: position

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      
    allow_integration_in_goal_trajectories: true
    state_publish_rate: 1000.0 # Defaults to 50
    use_stamped_vel: false

